### ISSUE TITLE
401 Captcha needed for Musixmatch search engine.

### ISSUE THREAD

**Issue by CookieGMVN** [LewdHuTao/lyrics-api#2] opened 2024-09-08 18:02 UTC
Hi there, first, thanks a lot about your project!

I have tried to self-hosted your project, and it worked flawlessly at first, but then if the request rate increased, the Musixmatch search engine returned with the error:

```txt
[ERROR] Error: Error: {"message":{"header":{"status_code":401,"execute_time":0.004,"hint":"captcha"}}}
```

I just want to know if this is possible to fix, or are there any workarounds that I can do to the server.

Again, thanks for this awesome project!

**Comment by LewdHuTao** [comment] 2024-09-09 00:47
This is actually a known issue with the musixmatch search engine. I'll try to look into this issue in a day or two and I'll let you know if I'm able to fix this issue

**Comment by LewdHuTao** [comment] 2024-09-11 03:18
I've already pushed a fix to a new branch, but it still needs testing before I can merge it into the main branch. I’d really appreciate it if you could help test the fix (#3)

**Comment by CookieGMVN** [comment] 2024-09-11 07:31
I will test the fix asap. Thank you!

**Comment by LewdHuTao** [comment] 2024-09-12 08:49
> I will test the fix asap. Thank you!

how things are going? did you still get captcha error on the fix branch?

**Comment by CookieGMVN** [comment] 2024-09-12 10:28
Just deployed the fix on my server, and it seems doesn't worked:
![image](https://github.com/user-attachments/assets/c2bc4b41-6c41-446e-b396-ec24293dc696)

**Comment by LewdHuTao** [comment] 2024-09-12 12:32
> Just deployed the fix on my server, and it seems doesn't worked:
> ![image](https://github.com/user-attachments/assets/c2bc4b41-6c41-446e-b396-ec24293dc696)
> 

can you tell me how you reproduce that error?

**Comment by CookieGMVN** [comment] 2024-09-12 13:20
This is my method to get the lyrics:
```ts
    private async getLyricsFromTitle(title: string) {
        try {
            const track = await axios.get(process.env.LYRICS_API_URL + "/youtube/lyrics/?title=" + encodeURIComponent(title));
            if (!track.data) return undefined;
            return {
                artwork: track.data.artwork_url,
                trackName: track.data.track_name,
                artistName: track.data.artist_name,
                lyrics: track.data.lyrics
            }
        } catch(e) {
            return undefined;
        }
    }
```

Then, I just called this method, and I have the following error. In the method, I am not using the token that sent from the server, so I think the rate limiting is from the token establishing.

**Comment by LewdHuTao** [comment] 2024-09-12 14:05
I'll make it so that a new token is used for every new request, instead of relying on the token saved in cookies. It's getting pretty late for me right now so I'll push a new fix by tomorrow.

**Comment by LewdHuTao** [comment] 2024-09-13 02:25
Unfortunately using new token for every new request is still giving the same error and can confirm they did check the ip address everytime there is a new request. I have try a few workarounds but none of them work but here things you can do:

- use multiple proxies (ip rotation)
- rotate with other search engine

if you want to use musixmatch and not the other search engine you can use multiple proxies/ip rotation. I already test the proxies method and can confirm it's working (well im not really using proxies but using multiple api with different ip address). 

```js
import axios from 'axios';

// Use user agents
// User agents is not working
// const USER_AGENTS = [
//   'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/91.0',
//   'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0',
// ];


// Use proxies
const API_ENDPOINTS = [
  'http://localhost:3000/musixmatch/lyrics',
  'https://lyrics.shittybot.xyz/musixmatch/lyrics',
];

async function fetchLyricsWithAgentAndEndpoint(title: string, userAgent: string, apiEndpoint: string) {
  try {
    const response = await axios.get(`${apiEndpoint}?title=${encodeURIComponent(title)}`, {
    // No longer use as user agent do not work
    //   headers: {
    //     'User-Agent': userAgent,
    //   },
    });

    if (!response.data) return undefined;

    return {
      artwork: response.data.artwork_url,
      trackName: response.data.track_name,
      artistName: response.data.artist_name,
      lyrics: response.data.lyrics,
    };
  } catch (error) {
    console.error(`Error with User-Agent "${userAgent}" on API "${apiEndpoint}": ${error as string}`);
    return undefined;
  }
}

export default async function fetchLyrics(title: string) {
  for (const apiEndpoint of API_ENDPOINTS) {
    for (const userAgent of USER_AGENTS) {
      const result = await fetchLyricsWithAgentAndEndpoint(title, userAgent, apiEndpoint);
      if (result) {
        return result;
      }
    }
  }

  console.log('Lyrics not found with any User-Agent or API endpoint.');
  return undefined;
}

fetchLyrics("Title here").then((result) => {
  if (result) {
    console.log(result);
  } else {
    console.log("Lyrics not found or an error occurred.");
  }
});
```

**Closed** 2024-09-21 13:24 UTC
Labels: bug

**Comment by brunoman4006** [comment] 2025-05-09 17:24
Not sure if repoening this, but i did found on the documentation that you need an API key in order to make musixmatch work, maybe that's the reason on why the search engine fails?

![Image](https://github.com/user-attachments/assets/a9d1f241-ba24-4b1e-b30f-d6af3491e3bd)

**Comment by CookieGMVN** [comment] 2025-05-09 17:32
@brunoman4006 Absolutely not. This project is using MXM's web API, not the official API, so it doesn't need an API key to work.

**Comment by brunoman4006** [comment] 2025-05-09 18:14
That certainly checks out
